#!/bin/bash
set -euo pipefail

PRUNE=0
for arg in "$@"; do
  case "$arg" in
    --prune)
      PRUNE=1
      ;;
    -h|--help)
      echo "Usage: $0 [--prune]"
      echo
      echo "  --prune  Remove globally installed skills that are not listed in scripts/sync/skills.json."
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      echo "Usage: $0 [--prune]" >&2
      exit 2
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
BASE_RULES="$REPO_DIR/rules/agents.md"
LOCAL_RULES="$REPO_DIR/rules/agents.local.md"
FINAL_RULES="$REPO_DIR/rules/agents.final.md"

echo "Pulling latest in $REPO_DIR..."
git -C "$REPO_DIR" pull --ff-only

{
  printf '%s\n\n%s\n\n---\n\n' \
    "# Agent Instructions" \
    "Generated by scripts/sync/sync.sh from rules/agents.md and optional rules/agents.local.md. Do not edit directly."
  cat "$BASE_RULES"

  if [ -f "$LOCAL_RULES" ]; then
    printf '\n---\n\n## Local Overrides\n\n'
    cat "$LOCAL_RULES"
  fi
} > "$FINAL_RULES"

echo "Generated: rules/agents.final.md"

# Symlink only for installed agents
SKILL_AGENTS=()

if command -v claude >/dev/null 2>&1; then
  mkdir -p "$HOME/.claude"
  ln -sf "$FINAL_RULES" "$HOME/.claude/CLAUDE.md"
  echo "Linked: ~/.claude/CLAUDE.md -> rules/agents.final.md"
  SKILL_AGENTS+=(claude-code)
else
  echo "Skipping Claude Code setup: 'claude' is not installed"
fi

if command -v codex >/dev/null 2>&1; then
  mkdir -p "$HOME/.codex"
  ln -sf "$FINAL_RULES" "$HOME/.codex/AGENTS.md"
  echo "Linked: ~/.codex/AGENTS.md -> rules/agents.final.md"
  SKILL_AGENTS+=(codex)
else
  echo "Skipping Codex setup: 'codex' is not installed"
fi

# Cursor User Rules are not filesystem-synced; copy from rules/agents.final.md in Settings if you want them.
if command -v cursor >/dev/null 2>&1; then
  SKILL_AGENTS+=(cursor)
else
  echo "Skipping Cursor skills: 'cursor' is not on PATH (install Shell Command from Cursor command palette)"
fi

# openclaw has no PATH binary; presence of ~/.openclaw is the install signal.
if [ -d "$HOME/.openclaw" ]; then
  SKILL_AGENTS+=(openclaw)
else
  echo "Skipping openclaw skills: ~/.openclaw not found"
fi

MANIFEST="$REPO_DIR/scripts/sync/skills.json"

# Install skills only from stable manifest (portable across machines)
if [ -f "$MANIFEST" ]; then
  echo "Using skills manifest: $MANIFEST"

  if [ ${#SKILL_AGENTS[@]} -eq 0 ]; then
    echo "No supported agent installations found; skipping skill sync"
  else
    echo "Installing skills for agents: ${SKILL_AGENTS[*]}"

    jq -r '.skills[] | "\(.name) \(.source)"' "$MANIFEST" |
    while read -r name source; do
      echo "Installing skill: $name from $source"
      npx skills add "$source" -g -y -a "${SKILL_AGENTS[@]}" -s "$name" </dev/null 2>/dev/null || echo "  Failed: $name"
    done

    if [ "$PRUNE" -eq 1 ]; then
      LOCKFILE="$HOME/.agents/.skill-lock.json"
      if [ -f "$LOCKFILE" ]; then
        echo "Pruning skills missing from manifest"
        jq -r \
          --argjson manifest "$(jq -c '[.skills[].name]' "$MANIFEST")" \
          '(.skills // {}) | keys[] | select(. as $name | $manifest | index($name) | not)' \
          "$LOCKFILE" |
        while read -r skill_name; do
          [ -n "$skill_name" ] || continue
          echo "Removing stale skill: $skill_name"
          npx skills remove "$skill_name" -g -y </dev/null 2>/dev/null || echo "  Failed to remove: $skill_name"
        done
      else
        echo "No global skill lockfile found; skipping prune"
      fi
    else
      echo "Skipping prune. Use --prune to remove skills missing from manifest."
    fi
  fi
else
  echo "No skills manifest found at $MANIFEST"
fi

echo "Done."
