#!/bin/bash
set -euo pipefail

SKILLS_CLI_VERSION="${SKILLS_CLI_VERSION:-1.5.7}"

if [ "$#" -gt 0 ]; then
  echo "Usage: $0" >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
BASE_RULES="$REPO_DIR/rules/agents.md"
LOCAL_RULES="$REPO_DIR/rules/agents.local.md"
FINAL_RULES="$REPO_DIR/rules/agents.final.md"

echo "Pulling latest in $REPO_DIR..."
git -C "$REPO_DIR" pull --ff-only

{
  printf '%s\n\n%s\n\n---\n\n' \
    "# Agent Instructions" \
    "Generated by scripts/sync/sync.sh from rules/agents.md and optional rules/agents.local.md. Do not edit directly."
  cat "$BASE_RULES"

  if [ -f "$LOCAL_RULES" ]; then
    printf '\n---\n\n## Local Overrides\n\n'
    cat "$LOCAL_RULES"
  fi
} > "$FINAL_RULES"

echo "Generated: rules/agents.final.md"

# Symlink only for installed agents
SKILL_AGENTS=()

if command -v claude >/dev/null 2>&1; then
  mkdir -p "$HOME/.claude"
  ln -sf "$FINAL_RULES" "$HOME/.claude/CLAUDE.md"
  echo "Linked: ~/.claude/CLAUDE.md -> rules/agents.final.md"
  SKILL_AGENTS+=(claude-code)
else
  echo "Skipping Claude Code setup: 'claude' is not installed"
fi

if command -v codex >/dev/null 2>&1; then
  mkdir -p "$HOME/.codex"
  ln -sf "$FINAL_RULES" "$HOME/.codex/AGENTS.md"
  echo "Linked: ~/.codex/AGENTS.md -> rules/agents.final.md"
  SKILL_AGENTS+=(codex)
else
  echo "Skipping Codex setup: 'codex' is not installed"
fi

MANIFEST="$REPO_DIR/scripts/sync/skills.json"

# Install skills only from stable manifest (portable across machines)
if [ -f "$MANIFEST" ]; then
  echo "Using skills manifest: $MANIFEST"

  if [ ${#SKILL_AGENTS[@]} -eq 0 ]; then
    echo "No supported agent installations found; skipping skill sync"
  else
    echo "Installing skills for agents: ${SKILL_AGENTS[*]}"

    jq -r '.skills[] | "\(.name) \(.source)"' "$MANIFEST" |
    while read -r name source; do
      echo "Installing skill: $name from $source"
      npx "skills@$SKILLS_CLI_VERSION" add "$source" -g -y -a "${SKILL_AGENTS[@]}" -s "$name" </dev/null 2>/dev/null || echo "  Failed: $name"
    done
  fi
else
  echo "No skills manifest found at $MANIFEST"
fi

echo "Done."
